_name_or_path:
    value: Qwen/Qwen3-14B
_wandb:
    value:
        cli_version: 0.21.1
        e:
            xdn6p2zgpo8y2y3bal0s8bi2npkko9px:
                args:
                    - --config
                    - ../../configs/Qwen3-14B/DPO/config_dpo.yaml
                codePath: training/open-r1/src/open_r1/dpo.py
                codePathLocal: open_r1/dpo.py
                cpu_count: 120
                cpu_count_logical: 240
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "389047648256"
                        used: "67544485888"
                email: miyako.s6105@gmail.com
                executable: /home/Competition2025/P02/P02U024/openr1/bin/python3
                git:
                    commit: 79bf918d710c8c5a5226c180cac1f61e4304a519
                    remote: git@github.com:Damin3927/llm2025compet.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-3d5f69ef-69c0-f1ec-b20e-f8de46fd66b0
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-68629e3e-bfff-274b-4bdc-b64514f175d2
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-d73faf83-f29c-2c33-e77d-f5f558c2c6ce
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-c26d72f9-4dd3-9b83-751c-b0245f3788d5
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-add23b3a-afa2-d640-2137-592137f71fd7
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-1464db32-4847-3e66-5a59-337df71e26a6
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-32d4ccf8-9b18-b4dd-220a-ee69a9dfa31c
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-130f6886-fca3-d1c8-74e3-1e4570677c73
                host: osk-gpu54
                memory:
                    total: "1622307418112"
                os: Linux-5.14.0-503.38.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: /home/Competition2025/P02/P02U024/llm2025compet/training/open-r1/src/open_r1/dpo.py
                python: CPython 3.12.11
                root: /home/Competition2025/P02/P02U024/llm2025compet/training/open-r1/src
                slurm:
                    cluster_name: osk-cluster
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "160"
                    cpus_per_task: "160"
                    gpus_on_node: "8"
                    gpus_per_node: "8"
                    gtids: "0"
                    job_cpus_per_node: 160(x3)
                    job_cpus_per_node_pack_group_0: 160(x3)
                    job_gid: "11052"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_id: "344553"
                    job_name: dpo-14b
                    job_nodelist: osk-gpu[54,56,91]
                    job_num_nodes: "3"
                    job_partition: P02
                    job_qos: normal
                    job_uid: "11052"
                    job_user: P02U024
                    jobid: "344553"
                    launch_node_ipaddr: 192.168.11.54
                    localid: "0"
                    mpi_type: pmix_v3
                    nnodes: "3"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: osk-gpu[54,56,91]
                    nprocs: "3"
                    ntasks: "3"
                    ntasks_per_node: "1"
                    pmix_mapping_serv: (vector,(0,3,1))
                    pmixp_abort_agent_port: "38967"
                    prio_process: "0"
                    procid: "0"
                    srun_comm_host: 192.168.11.54
                    srun_comm_port: "40299"
                    step_gpus: 0,1,2,3,4,5,6,7
                    step_id: "0"
                    step_launcher_port: "40299"
                    step_nodelist: osk-gpu[54,56,91]
                    step_num_nodes: "3"
                    step_num_tasks: "3"
                    step_tasks_per_node: 1(x3)
                    stepid: "0"
                    submit_dir: /home/Competition2025/P02/P02U024
                    submit_host: osk-cpu01
                    task_pid: "26219"
                    tasks_per_node: 1(x3)
                    topology_addr: osk-gpu54
                    topology_addr_pattern: node
                    umask: "0022"
                    working_cluster: osk-cluster:10.255.255.100:6817:9728:109
                startedAt: "2025-08-10T06:13:16.518560Z"
                writerId: xdn6p2zgpo8y2y3bal0s8bi2npkko9px
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "3":
                - 7
                - 13
                - 19
                - 66
            "4": 3.12.11
            "5": 0.21.1
            "6": 4.54.1
            "9":
                "1": transformers_trainer
            "12": 0.21.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen3ForCausalLM
attention_bias:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
base_model_attribute_name:
    value: model
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
beta:
    value: 0.1
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 151643
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: 42
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_num_proc:
    value: 12
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_dropout:
    value: true
disable_tqdm:
    value: false
discopop_tau:
    value: 0.05
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
f_alpha_divergence_coef:
    value: 1
f_divergence_type:
    value: reverse_kl
finetuning_task:
    value: null
force_use_ref_model:
    value: false
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generate_during_eval:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
head_dim:
    value: 128
hidden_act:
    value: silu
hidden_size:
    value: 5120
hub_always_push:
    value: false
hub_model_id:
    value: Qwen3-14B-DPO-test
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 17408
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_pad_token_id:
    value: -100
label_smoothing:
    value: 0
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
ld_alpha:
    value: null
learning_rate:
    value: 5e-06
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: info
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: data/Qwen3-14B-DPO-test/runs/Aug10_15-11-45_osk-gpu54
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 1
logging_strategy:
    value: steps
loss_type:
    value: sigmoid
loss_weights:
    value: null
lr_scheduler_type:
    value: linear
max_completion_length:
    value: null
max_grad_norm:
    value: 0.2
max_length:
    value: 32768
max_position_embeddings:
    value: 40960
max_prompt_length:
    value: 512
max_steps:
    value: -1
max_window_layers:
    value: 40
metric_for_best_model:
    value: null
min_length:
    value: 0
model/num_parameters:
    value: 10910720
model_adapter_name:
    value: null
model_init_kwargs:
    value: null
model_type:
    value: qwen3
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 40
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 40
num_key_value_heads:
    value: 8
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: paged_adamw_8bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: data/Qwen3-14B-DPO-test
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: true
pad_token_id:
    value: null
padding_free:
    value: false
padding_value:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: Qwen/Qwen3-14B
            bias: none
            corda_config: null
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 16
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            qalora_group_size: 16
            r: 8
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - o_proj
                - v_proj
                - q_proj
                - k_proj
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 1
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
precompute_ref_batch_size:
    value: null
precompute_ref_log_probs:
    value: false
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
ref_adapter_name:
    value: null
ref_model_init_kwargs:
    value: null
ref_model_mixup_alpha:
    value: 0.6
ref_model_sync_steps:
    value: 512
reference_free:
    value: false
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value: null
rope_theta:
    value: 1000000
rpo_alpha:
    value: null
run_name:
    value: data/Qwen3-14B-DPO-test
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 1
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sliding_window:
    value: null
suppress_tokens:
    value: null
sync_ref_model:
    value: false
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
tools:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: bfloat16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.54.1
truncation_mode:
    value: keep_end
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_liger_loss:
    value: false
use_logits_to_keep:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
use_weighting:
    value: false
vocab_size:
    value: 151936
warmup_ratio:
    value: 0.03
warmup_steps:
    value: 0
weight_decay:
    value: 0
