_wandb:
    value:
        cli_version: 0.21.0
        e:
            k1i7s96q8yffqeslbsaci9lkmpowkhek:
                args:
                    - --dataset
                    - do_not_answer_response
                    - --judge
                    - gpt-4.1-mini-2025-04-14
                codePath: evaluation/dna/eval.py
                codePathLocal: evaluation/dna/eval.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "139380985856"
                email: m.junichiro@gmail.com
                executable: /home/user/.venv/bin/python3
                git:
                    commit: 83bb00eec03d2d925e982c83eba62510f982a99a
                    remote: git@github.com:Damin3927/llm2025compet.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-cc1f523e-ede0-eaba-c453-9cf94d0b05ea
                host: docker-desktop
                memory:
                    total: "15710986240"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /app/evaluation/dna/eval.py
                python: CPython 3.12.11
                root: /app
                startedAt: "2025-07-27T01:17:36.738772Z"
                writerId: k1i7s96q8yffqeslbsaci9lkmpowkhek
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 49
                - 95
            "2":
                - 49
                - 95
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
dataset:
    value: do_not_answer_response.csv
model:
    value: gpt-4.1-mini-2025-04-14
